### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by avstudnitz**

### CODE REVIEW

**Comment by gowrizrh** [comment]
I'm happy for this to be standalone module which provides some quality of life features in the admin to manage async events provided the user of this module knows what they are doing.

The original module does not allow adding / deleting subscribers in the admin for the following reasons

* Subscriptions are not always HTTP based. They can be AWS SQS, EventBridge, Azure Service Bus, Azure EventGrid, Slack, AMQP, etc. This is just something to keep in mind for now. We may want the ability to add other types of subscriptions.
* Admin users could potentially add any subscription they want. Say a user with ill intent is creating subscriptions to an external endpoint that is malicious to collect PII.
* The above is only really an issue when we allow a subscription to be deleted, (which means logs related will be deleted) - This becomes a problem when a user has added a subscription to another service collecting PII in the background for a while and before anyone has noticed, they've deleted the subscription. Effectively removing all traces. The logs table are intended to be "append-only" and we are able to journal it with every single event.

One other potential area that allowing delete could affect is the indexing, this is something I'll have to investigate whether to change the approach or not. Short version, the indexer takes a distinct value of event names in the subscriber table instead of the merged `async_events.xml` to determine scopes / dimensions to index. An assumption that a subscription is not always deleted let us always only index what's needed, keeping opensearch clean of empty indices.

Could we remove allowing a user to delete the subscription for now while we have a chat on approaching this in the future? The workaround for now would be - being able to disable a subscription.

**Comment by avstudnitz** [comment]
@gowrizrh Thanks for your feedback. I'll work on it today - next Hackathon :-)

> Admin users could potentially add any subscription they want. Say a user with ill intent is creating subscriptions to an external endpoint that is malicious to collect PII.

The same admin user can use his credentials to do that via REST API.

> Could we remove allowing a user to delete the subscription for now while we have a chat on approaching this in the future? The workaround for now would be - being able to disable a subscription.

We can do that, I am fine with that.
But, in my opinion, being able to delete subcribers doesn't really mean an additional security risk. If it is a user with full rights, he has other ways to retreive the data he wants to have, simply by exporting customers / orders etc. The main risk would be to leave an active subscriber, continuing to export data after the admin user is gone, which will possibly never be spotted or only much later. But he can do that anyways, using the REST API.

**Comment by avstudnitz** [comment]
@gowrizrh I removed everything which has to do with the delete functionality. I added a note to the readme, linking to your comment with the security concerns.

**Comment by gowrizrh** [comment]
thanks @avstudnitz!

you're right. i think an admin user potentially misusing this is _one_ of the side effects. my underlying thought however is, if or not the entire thing should be fully reproducible from the beginning.

this currently wouldn't be 100% true of the module anyway in its true sense because we do not have a changelog for the subscriber (meaning when it was turned on or off).

the module also currently has a setting for a cron job which would go and clean logs over a configured amount of days. thinking retrospectively over this, i believe this shouldn't also happen. (atleast it's only opt-in for now)

i think i'll need to think around what it means to be fully replayable/reproduceable and take a stance.

we should definitely come back to this after that.

thank you for all the work! :smile: :heart:

**Review by gowrizrh — APPROVED** [review]
LGTM

**Pull request merged**
